version: "3.4"

services:

  app:
    build: ./app
    container_name: app
    ports:
      - 80:80
    volumes: 
      - ./app:/app
      - app_modules:/app/node_modules


volumes:
  app_modules:
    name: app_modules
